# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
    name = "About"
    url = "#about"
    weight = 1

[[main]]
    name = "Professional Development"
    url = "#prodev"
    weight = 2

[[main]]
    name = "Contact"
    url = "#contact"
    weight = 3

[[main]]
    name = "Meet"
    url = "#meet"
    weight = 4

[[main]]
    name = "Chat"
    url = "#chat"
    weight = 5

[[main]]
    name = "Teaching"
    url = "#teaching"
    weight = 6

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "files/cv.pdf"
#    weight = 70
